
//Question 1
var a = 3
var b = 2

var result = ternaryPractice()

console.log(result);

function ternaryPractice() {
    return a>b ? "True":"False"
}

//Question 2

var hotel = {
    name: 'Quay',
    rooms: 40,
    booked: 25,
    gym: true,
    roomTypes: ['twin', 'Double', 'Suite']

};

for(key in hotel) {
    console.log(`${key}: ${hotel[key]}`);
}

//Question 3
let array = [1, 2, 3, 4, 5, 6];

let squaredArray = array.map(num => num * num);

console.log(squaredArray);

//Question 4

/*
The DOM specifies how browsers should create a mdel of an HTML page 
and how JavaScript can access and update the contents of a web page while
it is in the browser window. The DOM tree is a model of a web page.
*/

//Question 5

/*
An XSS attack occurs when an attacker places malicious code into a website.
This happens when websites feature content created by many different people. 
For example, people can create profiles or contribute articles. A hacker can 
enter malicious code that gives them access to information in the DOM, the website's
cookines, and the session tokens. This could allow an attacker to access someone else's
account, where they can make purchases, post defamatory content,
or spread their malicious code further/faster. To protect against this, you should calidate the input
going to the server. Only allow visitors to input certain kinds of characters, double-check validation 
on the server before displaying user content, and ensure the database contains markup
and script from trusted sources. Do not create DOM fragments containing HTML from untrusted 
sources, make sure you are only inserting content generated by users into certain parts of the 
template files. and all potentially dangerous characters should be escaped as your data leaves the 
database. 
*/

//Question 6


<html lang="en">
  <head>
  <button id="myButton">Click me</button>
  </head>
</html>


document.getElementById('myButton').addEventListener('click', function (e) {
    this.innerText = "Changed the Text";
  });


  //6b
  var listItems = document.querySelectorAll("#myList li");
  listItems.forEach(function(item) {
      item.addEventListener("click", function() {
          listItems.forEach(function(li) {
              li.style.color = "blue";
          });
      });
  });

  //6c
  document.getElementById("anotherButton").addEventListener("click", function() {
    var paragraph = document.createElement("p");
    paragraph.textContent = "Here is a paragraph with some text!";
    document.getElementById("myDiv").appendChild(paragraph);
});